[versions]
compose = "1.5.4"
kotlin = "1.8.0"
core-ktx = "1.12.0"
lifecycle-runtime = "2.6.2"
activity-compose = "1.8.0"
compose-constraintLayout = "1.0.1"
material3-compose = "1.2.0-alpha10"
compose-navigation = "2.7.5"
runtime-compose = "2.6.2"
dagger-hilt = "2.48"
hilt-navigation-compose = "1.1.0"
timber = "5.0.1"
retrofit = "2.9.0"
okhttp = "4.9.3"
okhttp-login-interceptor = "4.9.3"
moshi = "2.9.0"
moshi-kotlin = "1.9.3"
firebaseBom = "32.5.0"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-constraint-layout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintLayout" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
material3-compose = { module = "androidx.compose.material3:material3", version.ref = "material3-compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "runtime-compose" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttplogginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-login-interceptor" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-kotlin" }
moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "moshi" }
firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom"}